name: Auto Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.email "github-actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions"

    - name: Push to Hugging Face Spaces
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git clone https://huggingface.co/spaces/dooehn/log-analyzer hf-space
        shopt -s extglob
        cp -r !(hf-space|.git|.github) hf-space/
        cd hf-space
        git add .
        git commit -m "Sync from GitHub repo on $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push https://dooehn:${HF_TOKEN}@huggingface.co/spaces/dooehn/log-analyzer